modLoader = "javafml"
loaderVersion = "[39,)"
license = "All rights reserved"
[[mods]]
modId = "smartpassword"
version = "0.7"
displayName = "SmartAutoPassword"
logoFile = ""
credits = "SmartAutoPassword"
authors = "Plinto"
description = '''Автоматически вводит пароли'''

[[dependencies.smartpassword]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.smartpassword]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,1.19)"
ordering = "NONE"
side = "BOTH"
